### ISSUE TITLE
Disable dependency scanning for tex artifacts (feature request)

### ISSUE THREAD

**Issue by vspiliop** [reallyinsane/mathan-latex-maven-plugin#8]
- Be able to disable dependency scanning for tex artifacts
- Or even better provide a filtering (inclusion or exclusion) mechanism via patterns

thanks!

**Comment by reallyinsane** [comment]
Hi Vassilis,

you're right that dependency scanning is enabled by default when dependencies are defined. My use cases were designed that the maven project is used to run LaTeX only. If you have dependencies in the project for other reasons this might be problematic.
 But the mechanism for including/excluding resources is there already. You can use the configuration ```resources``` to achieve this.

Please have a look at the [maven sample](https://github.com/reallyinsane/mathan-latex-maven-plugin/blob/master/mathan-latex-it/src/test/resources/configuration/resources/pom.xml) or [gradle sample](https://github.com/reallyinsane/mathan-latex-maven-plugin/blob/master/mathan-latex-it/src/test/resources/configuration/resources/build.gradle). It's handling includes but using excludes should be possible also. Please have a try and give me feedback if you still have problems.

**Comment by vspiliop** [comment]
Hi Matthias!

Thanks for your reply. It seems my use case is a bit different from what you had in mind for this plugin, but still it does what I would want it to do. This is just a possible performance improvement specifically for my use case. I use this plugin (together with others, e.g., a Plantuml one) to generate during build time diagrams and latex artefacts (mainly tables) for including them in the generate maven site documentation of the repo.

**Comment by reallyinsane** [comment]
Resolved with release 1.0.4
